//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SportsFacilities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SportsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SportsEntities object using the connection string found in the 'SportsEntities' section of the application configuration file.
        /// </summary>
        public SportsEntities() : base("name=SportsEntities", "SportsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SportsEntities object.
        /// </summary>
        public SportsEntities(string connectionString) : base(connectionString, "SportsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SportsEntities object.
        /// </summary>
        public SportsEntities(EntityConnection connection) : base(connection, "SportsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<facility> facilities
        {
            get
            {
                if ((_facilities == null))
                {
                    _facilities = base.CreateObjectSet<facility>("facilities");
                }
                return _facilities;
            }
        }
        private ObjectSet<facility> _facilities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the facilities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofacilities(facility facility)
        {
            base.AddObject("facilities", facility);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SportsModel", Name="facility")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class facility : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new facility object.
        /// </summary>
        /// <param name="facilityId">Initial value of the FacilityId property.</param>
        /// <param name="facilityName">Initial value of the FacilityName property.</param>
        public static facility Createfacility(global::System.Int32 facilityId, global::System.String facilityName)
        {
            facility facility = new facility();
            facility.FacilityId = facilityId;
            facility.FacilityName = facilityName;
            return facility;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FacilityId
        {
            get
            {
                return _FacilityId;
            }
            set
            {
                if (_FacilityId != value)
                {
                    OnFacilityIdChanging(value);
                    ReportPropertyChanging("FacilityId");
                    _FacilityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FacilityId");
                    OnFacilityIdChanged();
                }
            }
        }
        private global::System.Int32 _FacilityId;
        partial void OnFacilityIdChanging(global::System.Int32 value);
        partial void OnFacilityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FacilityName
        {
            get
            {
                return _FacilityName;
            }
            set
            {
                OnFacilityNameChanging(value);
                ReportPropertyChanging("FacilityName");
                _FacilityName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FacilityName");
                OnFacilityNameChanged();
            }
        }
        private global::System.String _FacilityName;
        partial void OnFacilityNameChanging(global::System.String value);
        partial void OnFacilityNameChanged();

        #endregion

    
    }

    #endregion

    
}
